---
deployment:
  targets:
    production:
      domain: campetapp.com
      path: /home/campetapp/public_html
      branch: main
      username: campetapp
  post_deployment:
    - export DEPLOYPATH=/home/campetapp/public_html
    - export PATH=/opt/cpanel/ea-php82/root/usr/bin:$PATH
    - cd $DEPLOYPATH
    - php artisan config:clear
    - php artisan view:clear
    - php artisan cache:clear
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan view:cache
